spring:
  application:
    name: eshop
  datasource:
    url: URL
    username: DB
    password: Pass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090


